upstream app_server {
    # fail_timeout=0 means we always retry an upstream even if it failed
    # to return a good HTTP response

    # for UNIX domain socket setups
    #server unix:/tmp/gunicorn.sock fail_timeout=0;

    # for a TCP configuration
    server dgenies-api:5000 fail_timeout=0;
}

server {
    # use 'listen 80 deferred;' for Linux
    # use 'listen 80 accept_filter=httpready;' for FreeBSD
    listen       8080;
    listen       [::]:8080;
    client_max_body_size 4G;

    # set the correct host(s) for your site
    server_name dgenies;

    keepalive_timeout 5;

    # path for static files
    #root /usr/share/nginx/html;


    location / {
        # serve index if resource not found
        try_files $uri $uri/ @proxy_to_app;
    }

    location /new-ui {
        alias /usr/share/nginx/html/;
        #index index.html;
        try_files $uri $uri /new-ui/index.html;
    }

    #location /assets/ {
    #    try_files $uri $uri/ @proxy_to_app;
    #}

    # needed to resolv icons when deployed in subfolder
    location ~ /static/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ @proxy_to_app;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;
        proxy_pass http://app_server;
    }
}
