#!/usr/bin/env python3

"""Prepare PAF file

Short desc: Prepare the PAF file from minimap output to be loaded by the program
Details: change coordinates of matches to be bounded one to another

Usage:
    prepare_paf.py -i IN -f FASTA1 -g FASTA2 -o OUT
    prepare_paf.py -v | --version

Options:
    -i --input=IN  Input PAF file generated by minimap
    -f --fasta1=FASTA1    First fasta file compared with minimap
    -g --fasta2=FASTA2    Second fasta file compared with minimap
    -o --output=OUT Output PAF file
    -h --help   Show this screen
    -v --version    Show version
"""

__NAME__ = "PreparePAF"
__VERSION__ = 0.1

import os
from docopt import docopt
from collections import OrderedDict


class Fasta:
    def __init__(self, fasta):
        self.fasta = fasta
        self.fai = fasta + ".fai"
        self.name = os.path.splitext(os.path.basename(fasta))[0]
        self.contigs = OrderedDict()
        self.total_length = 0
        self.__load()

    def __load(self):
        start = 0
        with open(self.fai, "r") as fai_file:
            for line in fai_file:
                parts = line.strip("\n").split("\t")
                length = int(parts[1])
                self.contigs[parts[0]] = {
                    "length": length,
                    "start": start
                }
                start += length
                self.total_length += length

    def get_contig(self, contig):
        return self.contigs[contig]

    def build_index(self, filename):
        with open(filename, "w") as idx:
            for contig, props in self.contigs.items():
                idx.write(contig + "\t" + str(props["length"]) + "\n")


def build_new_paf_file(paf_in: str, paf_out: str, fasta1: Fasta, fasta2: Fasta):
    with open(paf_in, "r") as paf:
        with open(paf_out, "w") as paf_o:
            for line in paf:
                parts = line.strip("\n").split("\t")
                q_name = parts[0]
                q_start = fasta1.get_contig(q_name)["start"]
                parts[0] = fasta1.name  # Change query name
                parts[1] = str(fasta1.total_length)  # Change length of query
                parts[2] = str(int(parts[2]) + q_start)  # Change start of query
                parts[3] = str(int(parts[3]) + q_start)  # Change end of query
                t_name = parts[5]
                parts[5] = fasta2.name  # Change target name
                t_start = fasta2.get_contig(t_name)["start"]
                parts[6] = str(fasta2.total_length)  # Change length of query
                parts[7] = str(int(parts[7]) + t_start)  # Change start for target
                parts[8] = str(int(parts[8]) + t_start)  # Change end for target
                paf_o.write("\t".join(parts) + "\n")


if __name__ == '__main__':
    args = docopt(__doc__)
    if args["--version"]:
        print(__NAME__, __VERSION__)
    else:
        if not os.path.exists(args["--fasta1"] + ".fai"):
            raise Exception("Fasta file %s is not indexed!" % args["--fasta1"])
        if not os.path.exists(args["--fasta2"] + ".fai"):
            raise Exception("Fasta file %s is not indexed!" % args["--fasta2"])
        fasta1 = Fasta(args["--fasta1"])
        fasta2 = Fasta(args["--fasta2"])
        build_new_paf_file(args["--input"], args["--output"], fasta1, fasta2)
        basedir = os.path.dirname(args["--output"])
        for fasta in [fasta1, fasta2]:
            idx_file = os.path.join(basedir, os.path.basename(fasta.name) + ".idx")
            fasta.build_index(idx_file)
